language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
before_script:
  - pip install filesystem_tree pyflakes pytest>=2.4 .
script: ./runtests.sh
notifications:
  email: false
branches:
  only:
    - master
