language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
install:
  - pip install --upgrade filesystem_tree pytest>=2.4
  - pip install ./
script:
  - ./runtests.sh
notifications:
  email: false
branches:
  only:
    - master
